# import by rendy
# Credits @ChillySkilly 
# dont't remove Credits
# From https://github.com/Randi356/VEGETA-USERBOT

from platform import uname
from userbot import ALIVE_NAME, CMD_HELP
from userbot.events import register

# ================= CONSTANT =================
DEFAULTUSER = str(ALIVE_NAME) if ALIVE_NAME else uname().node
# ============================================

@register(outgoing=True, pattern='^.dor(?: |$)(.*)')
async def typewriter(typew):
    typew.pattern_match.group(1)
    await typew.edit("**DOR DOR DOR DOR DOR DOR DOR DOR DOR DOR DOR DOR DOR DOR DOR DOR DOR DOR DOR DOR DOR DOR DOR DOR DOR DOR DOR DOR DOR DOR DOR DOR DOR DOR DOR DOR DOR DOR DOR DOR DOR DOR DOR DOR DOR DOR DOR DOR DOR DOR DOR HAHAHAHAHAHAHA HAHAHAHAHAHAHA HAHAHAHAHAHAHA HAHAHAHAHAHAHA HAHAHAHAHAHAHA HAHAHAHAHAHAHA HAHAHAHAHAHAHA HAHAHAHAHAHAHA HAHAHAHAHAHAHA HAHAHAHAHAHAHA HAHAHAHAHAHAHA HAHAHAHAHAHAHA HAHAHAHAHAHAHA HAHAHAHAHAHAHA DOR DOR DOR DOR DOR DOR DOR DOR DOR DOR DOR DOR DOR DOR DOR DOR DOR DOR DOR DOR DOR DOR DOR DOR DOR DOR DOR DOR DOR DOR HAHAHAHAHAHAHA HAHAHAHAHAHAHA DOR DOR DOR HAHAHAHAHAHAHA HAHAHAHAHAHAHA HAHAHAHAHAHAHA HAHAHAHAHAHAHA HAHAHAHAHAHAHA HAHAHAHAHAHAHA HAHAHAHAHAHAHA HAHAHAHAHAHAHA HAHAHAHAHAHAHA HAHAHAHAHAHAHA HAHAHAHAHAHAHA HAHAHAHAHAHAHA HAHAHAHAHAHAHA HAHAHAHAHAHAHA DOR DOR DOR DOR DOR DOR DOR DOR DOR DOR DOR DOR DOR DOR DOR DOR DOR DOR DOR DOR DOR DOR DOR DOR DOR DOR DOR DOR DOR DOR DOR DOR DOR DOR DOR DOR DOR DOR DOR DOR DOR DOR AWOKWOKWOKWOKAWOKWOKWOKWOKAWOKWOKWOKWOKAWOKWOKWOKWOKAWOKWOKWOKWOKAWOKWOKWOKWOKAWOKWOKWOKWOKAWOKWOKWOKWOKAWOKWOKWOKWOKAWOKWOKWOKWOKAWOKWOKWOKWOKAWOKWOKWOKWOKAWOKWOKWOKWOKAWOKWOKWOKWOKAWOKWOKWOKWOKAWOKWOKWOKWOKAWOKWOKWOKWOKAWOKWOKWOKWOKAWOKWOKWOKWOK.**")

@register(outgoing=True, pattern=r"^\.awok(?: |$)(.*)")
async def typewriter(typew):
    typew.pattern_match.group(1)
    await typew.edit("**AWOKWOKWOKWOKWOKWOKAWOKAWOKAWOKAEOKAWOKAWOKAWOKAWOKAWOKAWOKAWOKAWOKAWOKAWOKAWOKAWOKAWOKAWOKAWOKAEOKAWOKAWOKAWOKAWOKAWOKAWOKAWOKAWOKAWOKAWOKAWOKAWOKAWOKAWOKAWOKAWOKAWOKAWOKAWOKAWOKAWOKAWOKAWOKAWOKAWOKAWOKAWOKAEOKAWOKAWOAWEOKAWOKAWOKAWOKAWOKAWOKAWOKAWOKAWOKAWOKAWOKAWOKAWOKAWOKAWOKAWOKAWOKAWOKAWOKAWOKAWOKAWOKAWOKAWOKAWOKAWOKAWOKAWOKAWOKAWOKAWOKAWOKAWOKAWOKAEOKAEOKAWOKAWOKAWOKAWOKAWOKAWOKAWOKAWOKAWOKAWOKAWOKAWOKAWOKAWOKAEOKAEOKAWOKAWOKAWOKAWOKAWOKAEOKAWOKAWOKAWOKAWOKAWOKAWOKAWOKAWOKAWOKAWOKAEOKAWOKAEOKAWOKAWOKAWOKAEOKAWOKAEOKAWOKAWOKAWOWOKWOKWOLKWOKWOKWOKWOKEOKWOKWOKWOKWIKEOKWOKWOKWIKWOKWOKWOKWOKWOKEOKWOKWOKWOLWOKWOKWOKEOKWOKWOLWOLQOKWOKWOKWOLWOKWOKWOLWOKWOKEOKWOKEPKWOKWOKWOKWOKWOKWOKWOKWOKWOKWOKWOKWOKWOKWOKWOKWOKWOKWOKWOKWIKWOKWOKWOKEOLWOKWOKWOKWOKWOKWOKWOKWOKWOKWOKWOKWOKWOKWOKWOKWOKWOKWOKWOKWOKWOKWOKWOKWOKWOKWOKWOKWOKWOKWOKWOKWOKWOKWOKWOKWOKWOKWOKWOKWOKWOKWOKWOKWOKWOKWOKWOKWOKWOKWOKEOKWOKEOKWOKEOKWOKEOKWOKWOKWOKWOKWOKWOKWOKWOKWOKWOKWOKWOKWOKWOKWOKWOKWOKWOKWOKWOKWOKWOKWOKWOKWOKWOKWOKWOKWOKWOKWOKWOKWOKWOKWOKWOKWOKWOKWOKWOKWOKWOKEOKWOKWOKEOWOKWONETHRHEYWYEWOKRRUTEUEFJURJWOKAWOKAWOKSWKWOKWOKWOKWOKWOKWOKWOKWOKWOKWOKWOKWOKWOKQOKWOKWOKWOKWOKWOKWOKWOKWOKWOKWOKWOKWOKWOKWOKWOKWOKWOKWOLWOKWOKWOK.**")
  

@register(outgoing=True, pattern='^.alay(?: |$)(.*)')
async def typewriter(kontol):
    kontol.pattern_match.group(1)
    await kontol.edit("**GA ALAY ALAY LU MUKA KONTOL.**")
    
@register(outgoing=True, pattern='^\.bsk(?: |$)(.*)')
async def typewriter(memek):
    memek.pattern_match.group(1)
    await memek.edit("**BERISIK GUA MAU NONTON BOKEP DULU BYE NGTOD**")

@register(outgoing=True, pattern='^\.pep(?: |$)(.*)')
async def typewriter(pukii):
  pukii.pattern_match.group(1)
  await pukii.edit("**LO GIKES SEMUA KONTOL PELER GC AMPAS**")

CMD_HELP.update({
    "toxic7":
    "𝘾𝙤𝙢𝙢𝙖𝙣𝙙: `.dor`\
    \n↳ : hahaha goblok"
    "𝘾𝙤𝙢𝙢𝙖𝙣𝙙: `.awok`\
    \n↳ : liat awokwok"
}) 
          
CMD_HELP.update({
    "toxic8":
    "𝘾𝙤𝙢𝙢𝙖𝙣𝙙: `.alay`\
    \n↳ : lu kepo sia"
    "𝘾𝙤𝙢𝙢𝙖𝙣𝙙: `.brsk`\
    \n↳ : lu kepo sia"
    "𝘾𝙤𝙢𝙢𝙖𝙣𝙙: `.pep`\
    \n↳ : liat gikes"

})
