# import by rendy
# Credits @ChillySkilly 
# dont't remove Credits
# From https://github.com/Randi356/VEGETA-USERBOT

from platform import uname
from userbot import ALIVE_NAME, CMD_HELP
from userbot.events import register

# ================= CONSTANT =================
DEFAULTUSER = str(ALIVE_NAME) if ALIVE_NAME else uname().node
# ============================================

@register(outgoing=True, pattern='^.dor(?: |$)(.*)')
async def typewriter(typew):
    typew.pattern_match.group(1)
    await typew.edit("**DOR DOR DOR DOR DOR DOR DOR DOR DOR DOR DOR DOR DOR DOR DOR DOR DOR DOR DOR DOR DOR DOR DOR DOR DOR DOR DOR DOR DOR DOR DOR DOR DOR DOR DOR DOR DOR DOR DOR DOR DOR DOR DOR DOR DOR DOR DOR DOR DOR DOR DOR HAHAHAHAHAHAHA HAHAHAHAHAHAHA HAHAHAHAHAHAHA HAHAHAHAHAHAHA HAHAHAHAHAHAHA HAHAHAHAHAHAHA HAHAHAHAHAHAHA HAHAHAHAHAHAHA HAHAHAHAHAHAHA HAHAHAHAHAHAHA HAHAHAHAHAHAHA HAHAHAHAHAHAHA HAHAHAHAHAHAHA HAHAHAHAHAHAHA DOR DOR DOR DOR DOR DOR DOR DOR DOR DOR DOR DOR DOR DOR DOR DOR DOR DOR DOR DOR DOR DOR DOR DOR DOR DOR DOR DOR DOR DOR HAHAHAHAHAHAHA HAHAHAHAHAHAHA DOR DOR DOR HAHAHAHAHAHAHA HAHAHAHAHAHAHA HAHAHAHAHAHAHA HAHAHAHAHAHAHA HAHAHAHAHAHAHA HAHAHAHAHAHAHA HAHAHAHAHAHAHA HAHAHAHAHAHAHA HAHAHAHAHAHAHA HAHAHAHAHAHAHA HAHAHAHAHAHAHA HAHAHAHAHAHAHA HAHAHAHAHAHAHA HAHAHAHAHAHAHA DOR DOR DOR DOR DOR DOR DOR DOR DOR DOR DOR DOR DOR DOR DOR DOR DOR DOR DOR DOR DOR DOR DOR DOR DOR DOR DOR DOR DOR DOR DOR DOR DOR DOR DOR DOR DOR DOR DOR DOR DOR DOR AWOKWOKWOKWOKAWOKWOKWOKWOKAWOKWOKWOKWOKAWOKWOKWOKWOKAWOKWOKWOKWOKAWOKWOKWOKWOKAWOKWOKWOKWOKAWOKWOKWOKWOKAWOKWOKWOKWOKAWOKWOKWOKWOKAWOKWOKWOKWOKAWOKWOKWOKWOKAWOKWOKWOKWOKAWOKWOKWOKWOKAWOKWOKWOKWOKAWOKWOKWOKWOKAWOKWOKWOKWOKAWOKWOKWOKWOKAWOKWOKWOKWOK.**")

@register(outgoing=True, pattern=r"^\.awok(?: |$)(.*)")
async def typewriter(typew):
    typew.pattern_match.group(1)
    await typew.edit("**AWOKWOKWOKWOKWOKWOKAWOKAWOKAWOKAEOKAWOKAWOKAWOKAWOKAWOKAWOKAWOKAWOKAWOKAWOKAWOKAWOKAWOKAWOKAWOKAEOKAWOKAWOKAWOKAWOKAWOKAWOKAWOKAWOKAWOKAWOKAWOKAWOKAWOKAWOKAWOKAWOKAWOKAWOKAWOKAWOKAWOKAWOKAWOKAWOKAWOKAWOKAWOKAEOKAWOKAWOAWEOKAWOKAWOKAWOKAWOKAWOKAWOKAWOKAWOKAWOKAWOKAWOKAWOKAWOKAWOKAWOKAWOKAWOKAWOKAWOKAWOKAWOKAWOKAWOKAWOKAWOKAWOKAWOKAWOKAWOKAWOKAWOKAWOKAWOKAEOKAEOKAWOKAWOKAWOKAWOKAWOKAWOKAWOKAWOKAWOKAWOKAWOKAWOKAWOKAWOKAEOKAEOKAWOKAWOKAWOKAWOKAWOKAEOKAWOKAWOKAWOKAWOKAWOKAWOKAWOKAWOKAWOKAWOKAEOKAWOKAEOKAWOKAWOKAWOKAEOKAWOKAEOKAWOKAWOKAWOWOKWOKWOLKWOKWOKWOKWOKEOKWOKWOKWOKWIKEOKWOKWOKWIKWOKWOKWOKWOKWOKEOKWOKWOKWOLWOKWOKWOKEOKWOKWOLWOLQOKWOKWOKWOLWOKWOKWOLWOKWOKEOKWOKEPKWOKWOKWOKWOKWOKWOKWOKWOKWOKWOKWOKWOKWOKWOKWOKWOKWOKWOKWOKWIKWOKWOKWOKEOLWOKWOKWOKWOKWOKWOKWOKWOKWOKWOKWOKWOKWOKWOKWOKWOKWOKWOKWOKWOKWOKWOKWOKWOKWOKWOKWOKWOKWOKWOKWOKWOKWOKWOKWOKWOKWOKWOKWOKWOKWOKWOKWOKWOKWOKWOKWOKWOKWOKWOKEOKWOKEOKWOKEOKWOKEOKWOKWOKWOKWOKWOKWOKWOKWOKWOKWOKWOKWOKWOKWOKWOKWOKWOKWOKWOKWOKWOKWOKWOKWOKWOKWOKWOKWOKWOKWOKWOKWOKWOKWOKWOKWOKWOKWOKWOKWOKWOKWOKEOKWOKWOKEOWOKWONETHRHEYWYEWOKRRUTEUEFJURJWOKAWOKAWOKSWKWOKWOKWOKWOKWOKWOKWOKWOKWOKWOKWOKWOKWOKQOKWOKWOKWOKWOKWOKWOKWOKWOKWOKWOKWOKWOKWOKWOKWOKWOKWOKWOLWOKWOKWOK.**")
              


CMD_HELP.update({
    "toxic7":
    "𝘾𝙤𝙢𝙢𝙖𝙣𝙙: `.dor`\
    \n↳ : hahaha goblok"
    "𝘾𝙤𝙢𝙢𝙖𝙣𝙙: `.awok`\
    \n↳ : liat awokwok"
}) 
